# Cubo Mágico


In [1]:
#importações
import numpy as np

In [15]:
class MagicCube:
    def __init__(self,size: int = 3, sum_axis: int = 6):
        self.magic_cube = np.zeros((size,size))
        self.sum_axis = sum_axis
    
    def set_magic_cube(self,matrix):
        self.magic_cube = matrix
        
    def check_valid_cube(self):
        axis_column = self.magic_cube.sum(axis=0)
        if (not(axis_column[0] ==  axis_column[1] == axis_column[2] == self.sum_axis)):
            return False
        axis_row = self.magic_cube.sum(axis=1)
        if (not(axis_row[0] == axis_row[1] == axis_row[2] == self.sum_axis)):
            return False
        return sum(np.fliplr(self.magic_cube).diagonal()) == sum(self.magic_cube.diagonal())
        
    def check_imperfect_cube(self):
        axis_column = self.magic_cube.sum(axis=0)
        if (not(axis_column[0] ==  axis_column[1] == axis_column[2] == self.sum_axis)):
            return False
        axis_row = self.magic_cube.sum(axis=1)
        if (not(axis_row[0] == axis_row[1] == axis_row[2] == self.sum_axis)):
            return False
        return True
    def show_magic_cube(self):
        print(self.magic_cube)
        
        

In [16]:
cube_example = MagicCube(3,6)

In [20]:
cube_example.set_magic_cube(np.array([[1,3,2],[5,0,1],[0,3,3]]))

In [21]:
cube_example.show_magic_cube()

[[1 3 2]
 [5 0 1]
 [0 3 3]]


In [22]:
cube_example.check_imperfect_cube()

True

In [23]:
cube_example.check_valid_cube()

False

In [26]:
def find_how_many_magic_cube_3_3_sum_6():
    magic_cube_full = 0
    magic_cube_imperfect = 0
    cube_test = MagicCube(3,6)
    for x1 in range(7):
        for x2 in range(7):
            for x3 in range(7):
                for x4 in range(7):
                    for x5 in range(7):
                        for x6 in range(7):
                            for x7 in range(7):
                                for x8 in range(7):
                                    for x9 in range(7):
                                        cube_test.set_magic_cube(np.array([[x1,x2,x3],[x4,x5,x6],[x7,x8,x9]]))
                                        if cube_test.check_imperfect_cube():
                                            magic_cube_imperfect += 1
                                            if cube_test.check_valid_cube():
                                                magic_cube_full +=1
    print("Magic Imperfect Cube", magic_cube_imperfect)
    print("Magic Full", magic_cube_full)

In [27]:
find_how_many_magic_cube_3_3_sum_6()

Magic Imperfect Cube 406
Magic Full 34


In [31]:
def make_matrix_from_values(x1,x2,x3,x4,x5,x6):
    _123 = x1
    _132 = x2
    _213 = x3
    _231 = x4
    _312 = x5
    _321 = x6
    return np.array([[_123+_132,_213+_321,_231+_321],[_213+_231,_123+_321,_132+_321],[_312+_321,_132+_231,_123+_213]])

In [32]:
def find_how_many_magic_cube_3_3_sum_6_new_approach():
    magic_cube_full = 0
    magic_cube_imperfect = 0
    cube_test = MagicCube(3,6)
    for x1 in range(7):
        for x2 in range(7):
            for x3 in range(7):
                for x4 in range(7):
                    for x5 in range(7):
                        for x6 in range(7):
                            cube_test.set_magic_cube(make_matrix_from_values(x1,x2,x3,x4,x5,x6))
                            if cube_test.check_imperfect_cube():
                                magic_cube_imperfect += 1
                                if cube_test.check_valid_cube():
                                    magic_cube_full +=1
    print("Magic Imperfect Cube", magic_cube_imperfect)
    print("Magic Full", magic_cube_full)

In [33]:
find_how_many_magic_cube_3_3_sum_6_new_approach()

Magic Imperfect Cube 130
Magic Full 8


0.23529411764705882